const sisterList = [
    { id: 1, name: "Rameen Abid" },
    { id: 2, name: "Tanzeela Gohar" },
    { id: 3, name: "Hiba Ali" },
    { id: 4, name: "Maha Fatima" },
    { id: 5, name: "Amna Nazar" },
    { id: 6, name: "Areeba Hai" },
    { id: 7, name: "Fatima Batool" },
    { id: 8, name: "Yasha Waheed" },
    { id: 9, name: "Dur-e-Kashaf" },
    { id: 10, name: "Muntaha Riaz" },
    { id: 11, name: "Sheza Tariq" },
    { id: 12, name: "Memoona Tahir" },
    { id: 13, name: "Hiba Khalid" },
    { id: 14, name: "Zupash" },
    { id: 15, name: "Haleema Sadia Azhar" },
    { id: 16, name: "Laiba Zubair" },
    { id: 17, name: "Asma Temurie" },
    { id: 18, name: "Rida Saleem" },
    { id: 19, name: "Meerab Zafar" },
    { id: 20, name: "Mariam Abdullah" },
    { id: 21, name: "Sidra Ahmed" },
    { id: 22, name: "Binte Hafsa" },
    { id: 23, name: "Maham Mubashir" },
    { id: 24, name: "Laiba Ali" },
    { id: 25, name: "Khansa Malik" },
    { id: 26, name: "Sauda Khan" },
    { id: 27, name: "Leena Rahman" },
    { id: 28, name: "Fatima Shehzadi" },
    { id: 29, name: "Rabia Saleem" },
    { id: 30, name: "Bushra Tariq" },
    { id: 31, name: "Almas Fatima" },
    { id: 32, name: "Rida Abdul Ghafar" },
    { id: 33, name: "Sana Naaz" },
    { id: 34, name: "Noor Fatima" },
    { id: 35, name: "Nimra Aziz" }
];